# -*- coding: utf-8 -*-
"""uclu_polarite_incidelen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbJzxl33TFzkbODXTKrsb-7eXaX53lVl
"""

!pip install transformers torch datasets -q

from google.colab import files
import pandas as pd
import io

uploaded = files.upload()
df = pd.read_excel(io.BytesIO(list(uploaded.values())[0]))
print(df.shape)
df.head()

# Boş/gereksiz sütunu sil
df = df.drop(columns=['YORUMUN_POLARITESI'])
print(df.columns.tolist())

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="incidelen/xlm-roberta-base-turkish-sentiment-analysis",
    device=0
)

# Test et
print(classifier("Ürün çok kaliteli, paketleme harikaydı!"))

from tqdm import tqdm
import pandas as pd

def get_sentiment_with_polarity(text):
    try:
        result = classifier(str(text)[:512])[0]
        label = result['label'].lower()
        score = round(result['score'], 4)

        if label == 'positive':
            polarity = round(score, 4)
        elif label == 'negative':
            polarity = round(-score, 4)
        else:
            polarity = 0.0

        return label, score, polarity
    except:
        return "error", 0.0, 0.0

tqdm.pandas()

df[['sentiment', 'confidence', 'polarity']] = df['YORUM'].progress_apply(
    lambda x: pd.Series(get_sentiment_with_polarity(x))
)

df.head(10)

print(df['sentiment'].value_counts())
print("\nOrtalama Polarite:", df['polarity'].mean().round(4))
print("Pozitif oranı: %", round((df['sentiment']=='positive').mean()*100, 2))
print("Negatif oranı: %", round((df['sentiment']=='negative').mean()*100, 2))
print("Nötr oranı:    %", round((df['sentiment']=='neutral').mean()*100, 2))

df['kelime_sayisi'] = df['YORUM'].apply(lambda x: len(str(x).split()))

print(df['kelime_sayisi'].describe())
print("\nOrtalama kelime sayısı:", df['kelime_sayisi'].mean().round(1))
print("En kısa yorum:", df['kelime_sayisi'].min(), "kelime")
print("En uzun yorum:", df['kelime_sayisi'].max(), "kelime")

df[['YORUM', 'sentiment', 'polarity', 'kelime_sayisi']].head(10)



import matplotlib.pyplot as plt

colors = {'positive': '#2ecc71', 'negative': '#e74c3c', 'neutral': '#95a5a6'}
counts = df['sentiment'].value_counts()

plt.figure(figsize=(8, 5))
bars = plt.bar(counts.index, counts.values,
               color=[colors.get(k, '#aaa') for k in counts.index])
for bar, val in zip(bars, counts.values):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 10, str(val), ha='center', fontsize=11)

plt.title("incidelen XLM-RoBERTa — Duygu Dağılımı", fontsize=13)
plt.ylabel("Yorum Sayısı")
plt.savefig("incidelen_sentiment_chart.png", dpi=150)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ─── Dağılım hesapla ─────────────────────────────────────────────
dagilim     = df['sentiment'].value_counts()
dagilim_pct = df['sentiment'].value_counts(normalize=True) * 100

print("=== DUYGU SINIFI DAĞILIMI ===")
tablo = pd.DataFrame({
    'Sınıf': dagilim.index,
    'n':     dagilim.values,
    '%':     dagilim_pct.values.round(2)
})
print(tablo.to_string(index=False))
print(f"\nToplam yorum: {len(df):,}")

# ─── Pasta grafiği ───────────────────────────────────────────────
renk_map = {
    'positive': '#4CAF50', 'negative': '#F44336', 'neutral': '#2196F3',
    'pozitif':  '#4CAF50', 'negatif':  '#F44336', 'nötr':    '#2196F3',
}

etiketler = dagilim.index.tolist()
degerler  = dagilim.values.tolist()
renkler   = [renk_map.get(e, '#9E9E9E') for e in etiketler]

fig, ax = plt.subplots(figsize=(7, 7))

wedges, texts, autotexts = ax.pie(
    degerler,
    labels=None,
    autopct='%1.1f%%',
    colors=renkler,
    startangle=140,
    pctdistance=0.75,
    wedgeprops=dict(edgecolor='white', linewidth=2)
)

for autotext in autotexts:
    autotext.set_fontsize(13)
    autotext.set_fontweight('bold')
    autotext.set_color('white')

legend_labels = [
    f"{e}  (n={n:,}, %{p:.1f})"
    for e, n, p in zip(etiketler, degerler, dagilim_pct.values)
]
legend_patches = [
    mpatches.Patch(color=renkler[i], label=legend_labels[i])
    for i in range(len(etiketler))
]
ax.legend(
    handles=legend_patches,
    loc='lower center',
    bbox_to_anchor=(0.5, -0.12),
    fontsize=11,
    frameon=False
)

ax.set_title(
    "XLM-RoBERTa Duygu Sınıfı Dağılımı",
    fontsize=14, fontweight='bold', pad=20
)

plt.tight_layout()
plt.savefig("/content/duygu_dagilimi_pasta.png", dpi=300, bbox_inches='tight')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

dagilim     = df['sentiment'].value_counts()
dagilim_pct = df['sentiment'].value_counts(normalize=True) * 100

print("=== DUYGU SINIFI DAĞILIMI ===")
tablo = pd.DataFrame({
    'Sınıf': dagilim.index,
    'n':     dagilim.values,
    '%':     dagilim_pct.values.round(2)
})
print(tablo.to_string(index=False))
print(f"\nToplam yorum: {len(df):,}")

renk_map = {
    'positive': '#00b894',
    'negative': '#d63031',
    'neutral':  '#b2bec3',
    'pozitif':  '#00b894',
    'negatif':  '#d63031',
    'nötr':     '#b2bec3',
}

etiketler = dagilim.index.tolist()
degerler  = dagilim.values.tolist()
renkler   = [renk_map.get(e, '#636e72') for e in etiketler]

fig, ax = plt.subplots(figsize=(7, 7))
fig.patch.set_facecolor('white')
ax.set_facecolor('white')

wedges, texts, autotexts = ax.pie(
    degerler,
    labels=None,
    autopct='%1.1f%%',
    colors=renkler,
    startangle=140,
    pctdistance=0.72,
    wedgeprops=dict(edgecolor='white', linewidth=3, width=0.65)
)

for autotext in autotexts:
    autotext.set_fontsize(13)
    autotext.set_fontweight('bold')
    autotext.set_color('white')

# Ortaya toplam yorum sayısı
ax.text(0, 0, f"{len(df):,}\nyorum", ha='center', va='center',
        fontsize=13, fontweight='bold', color='#2d3436', linespacing=1.6)

legend_labels = [
    f"{e}  (n={n:,} | %{p:.1f})"
    for e, n, p in zip(etiketler, degerler, dagilim_pct.values)
]
legend_patches = [
    mpatches.Patch(color=renkler[i], label=legend_labels[i])
    for i in range(len(etiketler))
]
ax.legend(
    handles=legend_patches,
    loc='lower center',
    bbox_to_anchor=(0.5, -0.13),
    fontsize=11,
    frameon=False,
    labelcolor='#2d3436'
)

ax.set_title(
    "Duygu Sınıfı Dağılımı",
    fontsize=15, fontweight='bold', pad=22, color='#2d3436'
)

plt.tight_layout()
plt.savefig("/content/duygu_dagilimi_pasta.png", dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Grafik kaydedildi → /content/duygu_dagilimi_pasta.png")

